# Generated by Django 5.2.8 on 2025-11-20 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('BRL', 'BRL - Brazilian Real'), ('EUR', 'EUR - Euro')], default='BRL', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_access',
            field=models.BooleanField(default=False, verbose_name='External Access'),
        ),
        migrations.AddField(
            model_name='project',
            name='geography',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('PT', 'Portugal'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('MX', 'Mexico'), ('OTHER', 'Other')], default='BR', max_length=5, verbose_name='Geography'),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('AGRO_MINING', 'Agro & Mining'), ('BANKING_INSURANCE', 'Banking & Insurance'), ('CONSUMER_GOODS', 'Consumer Goods'), ('CPG_RETAIL', 'CPG & Retail'), ('ENERGY_UTILITIES', 'Energy & Utilities'), ('HEALTH_SERVICES', 'Health Services'), ('INDUSTRY_MANUFACTURING', 'Industry - Manufacturing - Logistics'), ('INFRASTRUCTURE_CONSTRUCTION', 'Infrastructure & Construction'), ('LIFE_SCIENCES_CHEMICAL', 'Life Sciences & Chemical'), ('PASSENGER_TRANSPORT', 'Passenger Transport'), ('PUBLIC_SECTOR', 'Public Sector, Education Sv & NGOs'), ('REAL_ESTATE', 'Real Estate'), ('RETAIL_DISTRIBUTION', 'Retail & Distribution'), ('SERVICES', 'Services'), ('TELECOM_MEDIA', 'Telecom & Media'), ('TRAVEL_HOTELS', 'Travel & Hotels')], default='SERVICES', max_length=50, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.costcenter', verbose_name='Cost Center'),
        ),
    ]
