# Generated by Django 5.2.8 on 2025-11-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_task_assigned_to_remove_task_project_issue'),
        ('timesheet', '0005_alter_timeentry_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
