# Generated by Codex cleanup
from django.db import migrations


def delete_task_contenttype(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    task_cts = ContentType.objects.filter(app_label='projects', model='task')
    for ct in task_cts:
        Permission.objects.filter(content_type=ct).delete()
        ct.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0006_delete_task'),
    ]

    operations = [
        migrations.RunPython(delete_task_contenttype, migrations.RunPython.noop),
    ]
