# Generated by Django 5.2.8 on 2025-11-25 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapp',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de escopos permitidos (ex.: projects:read, tasks:write)'),
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('event', models.CharField(choices=[('task.created', 'task.created'), ('task.updated', 'task.updated'), ('timeentry.created', 'timeentry.created'), ('timeentry.updated', 'timeentry.updated')], max_length=50)),
                ('secret', models.CharField(blank=True, help_text='Assinatura HMAC opcional', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.integrationapp')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
