# Generated by Django 5.2.8 on 2025-11-25 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_integrationapp_scopes_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.integrationapp')),
            ],
            options={
                'verbose_name': 'Log de requisição',
                'verbose_name_plural': 'Logs de requisição',
                'ordering': ['-created_at'],
            },
        ),
    ]
