# Generated by Django 5.2.8 on 2025-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_webhookdeliverylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationapp',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de escopos permitidos (ex.: projects:read, issues:write)'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event',
            field=models.CharField(choices=[('issue.created', 'issue.created'), ('issue.updated', 'issue.updated'), ('timeentry.created', 'timeentry.created'), ('timeentry.updated', 'timeentry.updated')], max_length=50),
        ),
    ]
