# Generated by Django 5.2.8 on 2025-11-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_partial_approvers_and_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['date', 'project'], 'verbose_name': 'Lançamento de horas', 'verbose_name_plural': 'Lançamentos de horas'},
        ),
    ]
