# Generated by Django 5.2.8 on 2025-11-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_task_assigned_to_remove_task_project_issue'),
        ('timesheet', '0004_alter_activity_options_alter_timeentry_options'),
    ]

    def _clear_orphan_tasks(apps, schema_editor):
        TimeEntry = apps.get_model('timesheet', 'TimeEntry')
        TimeEntry.objects.all().update(task=None)

    operations = [
        migrations.RunPython(_clear_orphan_tasks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.issue'),
        ),
    ]
