# Generated by Django 5.2.8 on 2025-11-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_project',
            field=models.ForeignKey(blank=True, help_text='Project this client user is restricted to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_users', to='projects.project', verbose_name='Client Project'),
        ),
    ]
