# Generated by Django 5.2.8 on 2025-11-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_client_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
            ],
            options={
                'verbose_name': 'External User',
                'verbose_name_plural': 'External Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
            ],
            options={
                'verbose_name': 'Internal User',
                'verbose_name_plural': 'Internal Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
