# Generated by Django 5.2.8 on 2025-11-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_externaluser_internaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_helpdesk', 'Can access Helpdesk module'), ('access_approvals', 'Can access Approvals module'), ('access_admin', 'Can access Administration module')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
