# Generated by Django 5.2.8 on 2025-11-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpdesk', models.BooleanField(default=False)),
                ('approvals', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group module access',
                'verbose_name_plural': 'Group module accesses',
            },
        ),
    ]
