# Generated by Django 5.2.8 on 2025-11-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_module_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_helpdesk', 'Can access Helpdesk module'), ('access_approvals', 'Can access Approvals module'), ('access_admin', 'Can access Administration module'), ('access_reports', 'Can access Reports module')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='groupmoduleaccess',
            name='reports',
            field=models.BooleanField(default=False),
        ),
    ]
