# Generated by Django 5.2.8 on 2025-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_externaluser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_tr',
            field=models.CharField(blank=True, help_text='Identificador de TR vinculado ao recurso.', max_length=50, verbose_name='Código TR'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_modality',
            field=models.CharField(blank=True, help_text='Modalidade de contratação do usuário.', max_length=100, verbose_name='Modalidade de Contratação'),
        ),
    ]
