# Generated by Django 5.2.8 on 2025-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_codigo_tr_user_employment_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Exigir atualização da senha no próximo login.', verbose_name='Forçar alteração de senha'),
        ),
    ]
