# Generated by Django 5.2.8 on 2025-11-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_ticket_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
